### ISSUE TITLE
Correção Exercício `0.5.1`

### ISSUE THREAD

**Issue by mathiasgheno** [GioTini/web-0.5.1#1]
# Correção Exercício `0.5.1`

> Considere o wireframe abaixo como um guia visual para um sistema web que faz listagem de tarefas considerando três status: Pendentes, Concluídas e Excluídas.  [Referência visual](https://i.imgur.com/AsfPVcN.jpg). 

O principal problema da sua entrega está na falta de otimização no uso do seu código CSS. Note a quantidade de código duplicado de propriedades entre `pendentes`, `concluidas` e  `excluidas`. 

https://github.com/GioTini/web-0.5.1/blob/679eff121ea923a044a35e7e65a3c4fbb4f779d0/style.css#L46-L75

Você pode evitar isso fazendo uso de duas classes. Adicionando em uma classe as propriedades comuns e tratando as exceções (ou sobreescritas) em outra classe. Veja um exemplo abaixo. 

```css
.item {
        border-radius: 10px;
        margin-left: 500px;
        margin-right: 500px;
        margin-top: 10px;
        margin-bottom: 10px;
        padding: 5px;
}

.excluida {
        border-color: rgb(62, 84, 88);
        background-color: rgb(62, 84, 88);
}
```

```html
<li class="item excluida">Reler Os Sete Maridos de Evelyn Hugo</li>
```

**Nota:** 8.5

[^1]: [Caminhos: entenda as diferenças entre absolutos e relativos](https://www.alura.com.br/artigos/caminhos-entenda-diferencas-entre-absolutos-relativos?gclid=CjwKCAjw9J2iBhBPEiwAErwpeZOH615fG9QWBpSN2UuIKVbpf6WWD9sknST-4DwVDHzcCBBuMOYuzhoCbNsQAvD_BwE)
[^2]: [CSS Selectors ─ Element Element Selector](https://www.w3schools.com/cssref/sel_element_element.php)
[^3]: [CSS Variables ─ An Introduction](https://youtu.be/PHO6TBq_auI)
[^4]: [HTML Lists](https://www.w3schools.com/html/html_lists.asp)
